### ISSUE TITLE
What are feature set for a basic media service?

### ISSUE THREAD

**Issue by Eagles2F** [cmusv-sc/Ericsson-Cloud-INI-Practicum-Fall2015#1]
1. Front-end
2. Back-end

**Comment by abhishekshivanna** [comment]
Off the top of my head I can think of the following backend services:
- user auth/user-metadata service
- images service
- movie metadata service
- movie ingestion service (not sure if this is a service or not)

I am thinking the front-end is one service that brings all of the above services together?
I'm sure I am missing many other things.. anything else that you can think of ?
